
server:
  port: 8085
  servlet:
    context-path: /api/v1

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost:3306/identity-service?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


