logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
#      hibernate:
#        SQL: DEBUG

server:
  port: 8081
  application:
    name: vehicle-service
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle-service?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
