spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: vehicle-service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/api/v1/vehicles/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
