spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: vehicle-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/vehicles/**
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/customers/**
