logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
#      hibernate:
#        SQL: DEBUG

server:
  port: 8082
  application:
    name: customer-service
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer-service?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

